### ISSUE TITLE
Dependencies "rviz" on the package.xml 

### ISSUE THREAD

**Issue by mjoosbl** [thesensorpeople/leuze_rsl_ros2_drivers#2]
Hello everyone,

Why does the package.xml have 'rviz' listed as a dependency instead of 'rviz2' for the leuze_description?  

https://github.com/thesensorpeople/leuze_rsl_ros2_drivers/blob/fa73630f31c5c445f7cb4a726ba7aafb864c0a96/leuze_description/package.xml#L32C1-L32C34
This applies to both exec_depend and test_depend

I asking because i get an Error:
_the following packages/stacks could not have their rosdep keys resolved to system dependencies: 
leuze_description: Cannor locate rosde definition for [rviz]_

Regards,
Markus Joos

**Comment by mrazmilan** [comment]
Hello Markus,
thank you for the issue description. I've managed to reproduce the problem on a fresh Ubuntu/ROS2 installation. The error appeared when running the "_rosdep install --from-paths ..._." command. It did not appear in my previous installation where I ended up having both _rviz_ and _rviz2_ dependencies in one installation, because of some experiments I had been performing.

The bugfix is now available in the main branch (you have probably already fixed this locally by using _rviz2_ instead of _rviz_ in the package.xml file).

Thanks a lot for finding this!

Kind regards

Milan
